Hantera rumstyper och rum #393
noQ-sweden/noQ-Frontend pull request #25
Opened 2024-08-06 11:57 UTC by natischmidt

2024-08-06 14:34 UTC, jani-at-noq requested changes
Functionality is ok, but some clean up is needed. Please comment about the ShelterPages, what is that temporary files used during expirements and can be removed or is there a plan going forward?

Good job!

2024-08-06 14:34 UTC, jani-at-noq commented on package.json
> +    "js-cookie": "^3.0.5",
Not used and can be removed

2024-08-06 14:34 UTC, jani-at-noq commented on public/edit.svg
We should use the FA icons instead (fa-pencil) in this case.

2024-08-06 14:34 UTC, jani-at-noq commented on public/recycle-bin-icon.svg
We should use fa-trash instead

2024-08-06 14:34 UTC, jani-at-noq commented on public/triangle.svg
Use FaCaretDown from react-icons/fa instead.

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/RoomPage/BinIcon.jsx
use fa icons instead.

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/RoomPage/EditIcon.jsx
use fa icons instead.

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/RoomPage/EditRoomTable.jsx
> +              <input type="text" value={type} onChange={handleInputChange(setType)} className="w-[400px] h-[38px] px-3 py-2 border bg-[#D9D9D9BF]" />
Should be drop-down list. Room type can only be one of two values :  'room' or 'woman-only'. If free text users will make mistakes.

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/ShelterPage/ArrowButton.jsx
Use fa icon instead. This file can be removed in that case.

2024-08-06 14:34 UTC, jani-at-noq commented on src/pages/ShelterPage.jsx
Shelter page is not linked to any other page (import). So this is dead code right now. Should this be removed?

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/ShelterPage/tailwind.config.js
Shelter page is not linked to any other page (import). So this is dead code right now. Should this be removed?

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/ShelterPage/TabSleepingPlaces.jsx
Remove empty file

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/ShelterPage/TabSleepingPlaceTypes.jsx
Remove empty file

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/ShelterPage/TabServices.jsx
Remove empty file

2024-08-06 14:34 UTC, jani-at-noq commented on src/components/ShelterPage/TabOtherInfo.jsx
Remove empty file

2024-08-06 16:05 UTC, jani-at-noq commented on src/components/RoomPage/EditRoomTable.jsx
> +      const response = await axios.get('api/host/products');
Should use "api/host/hosts/{host_id}/products" as this API call returns all products for all hosts. Another option is to change the backend API "api/host/products" to return only products for the specific host and remove "api/host/hosts/{host_id}/products" from the backend. Either fix is ok for me.

2024-08-06 16:06 UTC, jani-at-noq commented on src/components/RoomPage/EditRoomTable.jsx
> +  }, []);
Fix Github actions test issue

2024-08-07 19:05 UTC, natischmidt commented on src/pages/ShelterPage.jsx
We have this site because Iiona started on it instead of "Roompage" i guess we keep it and import/use it when we implement more logic no need to remove it

2024-08-07 19:06 UTC, natischmidt commented on src/components/ShelterPage/TabSleepingPlaces.jsx
@IlkaA1

2024-08-07 19:06 UTC, natischmidt commented on src/components/ShelterPage/TabSleepingPlaces.jsx
can you check these files?

2024-08-11 12:02 UTC, natischmidt commented
@jani-at-noq did my best to fix these errors, most where from changes i didnt make or dont know about i asked @IlkaA1 to take a look aswell, as i havent worked with the tailwind stuff... can you review?

2024-08-12 18:38 UTC, jani-at-noq commented
Something seems to have gone wrong when you did the changes. If you run the frontend with mockapi the rooms are not listed. Looks like the login mockapi doesn't return the host_id anymore.
`Error: Could not find mock for: 
{
  "method": "get",
  "url": "api/host/hosts/undefined/products"
}`

2024-08-12 18:40 UTC, jani-at-noq commented
Also the edit.svg, recycle-bin-icon.svg and triangle.svg are back in the repo. Something went wrong with your rebase after your changed based on the review comments.

2024-08-15 17:16 UTC, jani-at-noq approved these changes

2024-08-15 17:36 UTC, merged