Fixade Checka in knappen.
noQ-sweden/noQ-Frontend pull request #38
Opened 2024-09-15 20:04 UTC by AbubakerSalah

2024-09-16 16:42 UTC, jani-at-noq commented
När man trycker på Incheckning knappen får man följande vy.
![image](https://github.com/user-attachments/assets/6d54f8b4-0dbc-4556-a4ca-4e3bb5f8baab)

Jag tänker att radet ska bara försvinna från listan istället. Man kan kanske få pop-up med bekräftelse (Vill du checka-in person xxxxx, ja/nej) om man vill ha det.

2024-09-16 16:51 UTC, jani-at-noq requested changes
Looks good! I've added some comments.

2024-09-16 16:51 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +    var pendingBookings = bookings.filter( function (booking) {
Ändra variabel namn från pendingBookings till confirmedBookings.

2024-09-16 16:51 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +    //noqMockApi.onPatch(urlPending).reply((config) => {
ta bort kommenterad rad

2024-09-16 16:51 UTC, jani-at-noq commented on src/components/Admin/IncomingGuests.jsx
> +                    setIncomingBookings(prevBookings =>
We should not update the list with date and time. We don't have logging for state changes for bookings yet, but that should be backend functionality and we don't have to set these values in the frontend. When backend gets the input to change booking state to checked_in, backend should log the date and time some way (to be defined).

2024-09-16 18:22 UTC, natischmidt requested changes
se Janis kommentar :)

2024-09-22 16:12 UTC, jani-at-noq approved these changes

2024-09-22 16:12 UTC, jani-at-noq commented
Ser ok ut för mig. Bra jobbat!

2024-09-23 21:39 UTC, merged