Checka ut brukare
noQ-sweden/noQ-Frontend pull request #41
Opened 2024-09-25 19:08 UTC by SelsabeelA

>  Beskrivning
> Som en admin på ett härbärge behöver jag kunna anteckna i systemet att brukaren lämnat härbärget så vi vet hur många och var brukarna är och sover.
> 
> Acceptance Criteria
> 
> AC1:
> Förutsatt en brukare lämnar härbärget och jag se knappen “checka ut”
> När klickar på den knappen
> Då registreras tiden för utcheckningen

![image](https://github.com/user-attachments/assets/84f6a763-30e3-4352-8254-666f284fbe67)

- Visar knappen "Utcheckning" bredvid gästerna som ännu inte checkades ut.
- Namnet tas bort när utcheckningen är klar.

2024-09-27 18:29 UTC, jani-at-noq requested changes
Två ställen där du har använt fel bokningsstatus. Annans bra.

Bra jobbat!

2024-09-27 18:29 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +        return booking.status.description === 'confirmed';
Status ska vara 'checked_in', inte 'confirmed' och end_date borde vara dagens datum. Outgoing = ska lämna boende idag.

2024-09-27 18:29 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +        bookings[idx].status.description = "checked_out"; // Updating status to 'checked_out'
Backend har status 'completed'.
ändra 'checked_out' till 'completed'

2024-09-28 07:07 UTC, jani-at-noq approved these changes
Bra jobbat. Ok för min del.

2024-09-30 07:03 UTC, natischmidt approved these changes

2024-09-30 08:05 UTC, AbubakerSalah approved these changes

2024-09-30 18:30 UTC, natischmidt approved these changes

2024-09-30 18:30 UTC, merged