feat: Update login flow and UI to handle first and last name display
noQ-sweden/noQ-Frontend pull request #43
Opened 2024-09-27 13:01 UTC by MarioDanilo0111

- Updated :
  - Added logic to store  and  in the login state.
  - Enhanced state logging for easier debugging of login-related data.

- Modified :
  - Captured  and  from the API response and set them in the login context.
  - Improved error handling for login failures.

- Updated :
  - Passed  and  to  to display user information in the header.
  - Handled cases where user information might be missing or undefined.

- Refactored :
  - Displayed  and  in the user avatar area.
  - Ensured the dropdown and logout functionality work as expected.
  - Added fallback for missing user information.

- Fixed :
  - Defined  helper function to format and display user’s full name in the page title.
  - Removed references to undefined functions and fixed errors in rendering user name.

- Updated :
  - Corrected login response to ensure  and  are populated for each user role (user, host, caseworker).
  - Enhanced mock API to return the correct  and  for specific users.

- Miscellaneous:
  - Added PropTypes validation in components where applicable.
  - Removed unnecessary  requirement in  component to resolve PropTypes warning.

2024-09-27 18:12 UTC, jani-at-noq requested changes
Ser bra ut. Några lint issues behöver fixas och kanske logik fel i ett if sats.

2024-09-27 18:12 UTC, jani-at-noq commented on src/components/Header/PageTitle.jsx
> +        {/* {login.username != null ? getName(login?.username) : "Välkommen"} */}
Ta borta kommenterad kod

2024-09-27 18:12 UTC, jani-at-noq commented on src/context/LoginProvider.jsx
> +import { createContext, useState, useEffect } from "react";
ta borta useEffect

2024-09-27 18:12 UTC, jani-at-noq commented on src/context/LoginProvider.jsx
> +      const response = await axios.post("/api/api/login/", loginData); // mock API call
ta borta kommentar om mock API call. Detta är API call, oavsett om vi kör till mock eller backend. Ingen skillnad

2024-09-27 18:12 UTC, jani-at-noq commented on src/context/LoginProvider.jsx
> +  /* useEffect(() => {
ta bort

2024-09-27 18:12 UTC, jani-at-noq commented on src/pages/HostPage.jsx
> +import axios from "./../api/AxiosNoqApi";
bra upptäckt

2024-09-27 18:15 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +    login.first_name = "HostTest";
first_name: HostTest -> Hosttest eller bara Host
last_name: UserTest -> Usertest eller bara User

2024-09-27 18:17 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +    login.first_name = "CaseTest";
first_name: CaseTest -> Casetest
last_name: WorkerTest -> Worker eller Workertest

2024-09-29 09:36 UTC, MarioDanilo0111 commented on src/components/Common/Card.jsx
> +    content: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
Får "Warning" meddelande på `Card` komponent, `Failed prop type: Invalid prop `content` of type `number` supplied to `Card`, expected `string`.`

2024-09-30 15:44 UTC, natischmidt requested changes
behövs några fix, reqeusta min review igen efter! :)

2024-10-01 08:58 UTC, natischmidt approved these changes

2024-10-01 19:34 UTC, merged