#523 rubrik
noQ-sweden/noQ-Frontend pull request #46
Opened 2024-10-05 16:41 UTC by AbubakerSalah

I updated the mockapi to return host details like region and address when a host logs in.

2024-10-06 11:29 UTC, natischmidt commented
Har du testat detta med backend? (inte bara mockapi)?

2024-10-06 20:49 UTC, jani-at-noq requested changes
Ändringen för mock api är i fel API.

2024-10-06 20:49 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +  first_name: "Frida",
Detta är fel API. Du behöver lägga till first_name och last_name till noqMockApi.onPost("api/login/").reply((config).

{
  "login_status": true,
  "message": "string",
  "groups": [
    "string"
  ],
  "host": {
    "region": {
      "id": 0,
      "name": "string"
    },
    "id": 0,
    "name": "string",
    "street": "string",
    "postcode": "",
    "city": ""
  },
  "first_name": "string",
  "last_name": "string"
}

2024-10-06 20:49 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +  first_name: "Frida",
hostInfo borde inte ändras, den är samma som i backend. Ok att ändra region om du vill.

2024-10-06 20:49 UTC, jani-at-noq commented on src/components/Header/Iconbar.jsx
> +        <div className="flex flex-co items-center">
Det finns ingen flex-co i tailwind, borde vara flex-col. Varför vill du ändra detta?

2024-10-06 20:49 UTC, jani-at-noq commented on src/App.jsx
> + import { createContext } from "react";
ta bort space

2024-10-07 08:38 UTC, AbubakerSalah commented on src/components/Header/Iconbar.jsx
> +        <div className="flex flex-co items-center">
Jag läste igenom koden och råkade radera av misstag.
Fixade till nu.

2024-10-07 08:52 UTC, AbubakerSalah commented on src/api/mockApi/mockApi.js
> +  first_name: "Frida",
Ska jag assigna First_name och last_name till empty strings i mockapi?

2024-10-07 16:32 UTC, jani-at-noq commented on src/api/mockApi/mockApi.js
> +    first_name:"",
You should use:
For User -> first_name = "User", last_name="User"
For Host -> first_name= "User", last_name="Host"
For Caseworker -> first_name = "User", last_name="Caseworker"

so first_name is the same for all, last_name is different. There is some if clauses below the row 45 you need to utilize.

2024-10-07 22:55 UTC, natischmidt commented
Hur går det med denna @AbubakerSalah

2024-10-08 05:28 UTC, AbubakerSalah commented
@natischmidt Det går sådär just nu, gjorde dom sista ändringarna i mockapi.

2024-10-10 20:43 UTC, jani-at-noq approved these changes
Ser bra ut.

2024-10-11 10:40 UTC, natischmidt approved these changes

2024-10-11 10:41 UTC, natischmidt commented
merge konflikter behöver lösas @AbubakerSalah

2024-10-11 13:27 UTC, merged