Address multiple UI bugs in the dashboard component
noQ-sweden/noQ-Frontend pull request #59
Opened 2024-10-15 19:03 UTC by MarioDanilo0111

2024-10-15 19:29 UTC, jani-at-noq commented
Testade lite och ser några problem.
Ingen namn eller initialer när man loggar in som host eller caseworker (user.host@test.nu, user.caseworker@test.nu)
![image](https://github.com/user-attachments/assets/c2584ff7-8c95-4a74-bba1-c2f1822fa49e)
![image](https://github.com/user-attachments/assets/99741151-4f97-469d-9b7c-bd614088f698)

2024-10-15 19:38 UTC, jani-at-noq requested changes
Host och caseworker namn har försvunnit i ändring för rubrik. Det senaste commit som funkar rätt är: 5ae9f56  Merge pull request #57 from noQ-sweden/Gästens-startsida-#585. Vi behöver fixa till first_name, last_name för host och caseworker.

Jag har komment med bild som visa hur det ser ut.

2024-10-15 19:38 UTC, jani-at-noq commented on src/components/Header/Header.jsx
> +            ? login.first_name[0]
I vilken situation kan first_name vara array?

2024-10-17 07:05 UTC, jani-at-noq commented
Jag kollar ikväll.

2024-10-17 15:33 UTC, tobbe-joh commented
liten fundering. när man loggar in som caseworker eller user så får man inte Överblick bredivid till höger. Host får User Host - Överblick men alltså inte User och Caseworker. Ska det vara så?

2024-10-17 17:15 UTC, jani-at-noq commented
> liten fundering. när man loggar in som caseworker eller user så får man inte Överblick bredivid till höger. Att logga in som "Host" blir: "User Host - Överblick" men alltså inte User och Caseworker. Ska det vara så?

Nej, det borde inte vara så. Header borde visa användarens namn och sidan man är i.

2024-10-17 17:17 UTC, jani-at-noq commented
verkar vara så att för user blir det ingen information om vilken sida man är i. För Caseworker är det bara Överblick som inte funkar. Alla andra sidor visar rätt information.

2024-10-17 18:07 UTC, MarioDanilo0111 commented
Jag ser vad du menar, kommer inte på vad som saknas just nu...
alla andra användare fungerar som det ska förutom Överblick för User och Caseworker som sagt.

2024-10-18 13:42 UTC, merged

2024-10-18 14:45 UTC, jani-at-noq commented
`  const { setHeader } = useHeader();
  setHeader("Överblick");`

Saknas för dom sidorna.