Skapa funktion se hur många nätter brukaren har sovit #626
noQ-sweden/noQ-Frontend pull request #67
Opened 2024-11-15 08:13 UTC by AbubakerSalah

Story
As a caseworker I need to see statistics about the users and how many nights they have been in the shelter, so I can Check that against the invoices.

2024-11-15 11:13 UTC, natischmidt commented
npm error Missing: react-side-effect@2.1.2 from lock file 

skrev via dm hur du fixar

2024-11-15 12:03 UTC, natischmidt requested changes
Se kommentar

2024-11-18 12:31 UTC, natischmidt approved these changes

2024-11-18 20:09 UTC, jani-at-noq requested changes
Some minor editorial changes to make the page look better (margins/padding or header section). Man ska ha margin of 6 on right and left (see pictures).

![image](https://github.com/user-attachments/assets/03e0a8aa-63b5-40b9-ae59-c6b237520b1e)

![image](https://github.com/user-attachments/assets/d749374f-11e4-4a1c-91a2-39274d984c57)

2024-11-21 03:09 UTC, merged