Move botpress to main instead of navbar
noQ-sweden/noQ-Frontend pull request #73
Opened 2024-12-10 16:04 UTC by SelsabeelA

For some reason running the code locally doesn't work for me, so i wrote the code without being able to see if it works until I can fix this issue on my end.

If it works fine for you, please do tell me by reviewing this.

All I did was move the botpress code from Navbar.jsx to Main.jsx.

2024-12-13 20:15 UTC, AbubakerSalah requested changes
The Botpress is not being rendered because the Main.jsx component is not linked within the App.jsx <Routes>.

2024-12-14 10:19 UTC, SelsabeelA commented
@AbubakerSalah Jag har fixat det nu och har sett till att den funkar lokalt, kan du snälla granska det igen?

2024-12-14 11:32 UTC, AbubakerSalah commented
@SelsabeelA Botpress är synlig på inloggningssidan, ska det vara så? Eller ska den synas först efter att man har loggat in?

2024-12-14 11:50 UTC, SelsabeelA commented
@AbubakerSalah Ja, exakt, det är det vi vill. Botpress ska vara synlig både på inloggningssidan och efter att man har loggat in.

2024-12-14 13:10 UTC, AbubakerSalah approved these changes

2024-12-14 13:18 UTC, AbubakerSalah commented
@SelsabeelA Snyggt jobbat!

2024-12-14 13:26 UTC, merged